Repository FRONT-END-BOOTCAMP-PLUS-3/dear-day, pull requests merged in 2025-04, with the labels that each got.

#228 ♻️ Refactor/#225 확인 버튼만 있는 Modal 추가
  components/modal/Modal.tsx
  components/modal/Modal.type.ts
  components/modal/ModalType.tsx
Labels: ♻️ Refactor

#229 🐛 Fix/#226 코스 삭제 방법 개선 및 오류 해결
  app/member/course/[course_id]/_components/EditHeader/EditHeader.tsx
  app/member/course/page.tsx
  components/BottomSheet/BottomSheet.tsx
  components/EventView/CourseDetailListView/CourseDetailListView.tsx
Labels: 🐛 Fix, ♻️ Refactor

#231 ✨ Feat/#227 회원가입페이지 이메일 인증 기능
  app/(anon)/join/_components/JoinForm/JoinForm.module.scss
  app/(anon)/join/_components/JoinForm/JoinForm.tsx
  app/api/auth/join/send-email/route.ts
  application/usecases/join/SendEmail.ts
  application/usecases/join/dto/SendEmailDto.ts
  package-lock.json
  package.json
Labels: ✨ Feature
